// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Read Root
    ///
    /// - Remark: HTTP `GET /`.
    /// - Remark: Generated from `#/paths///get(read_root__get)`.
    func read_root__get(_ input: Operations.read_root__get.Input) async throws -> Operations.read_root__get.Output
    /// Get Led Sections
    ///
    /// - Remark: HTTP `GET /api/led/sections`.
    /// - Remark: Generated from `#/paths//api/led/sections/get(get_led_sections_api_led_sections_get)`.
    func get_led_sections_api_led_sections_get(_ input: Operations.get_led_sections_api_led_sections_get.Input) async throws -> Operations.get_led_sections_api_led_sections_get.Output
    /// Turn On
    ///
    /// - Remark: HTTP `POST /api/led/on`.
    /// - Remark: Generated from `#/paths//api/led/on/post(turn_on_api_led_on_post)`.
    func turn_on_api_led_on_post(_ input: Operations.turn_on_api_led_on_post.Input) async throws -> Operations.turn_on_api_led_on_post.Output
    /// Turn Off
    ///
    /// - Remark: HTTP `POST /api/led/off`.
    /// - Remark: Generated from `#/paths//api/led/off/post(turn_off_api_led_off_post)`.
    func turn_off_api_led_off_post(_ input: Operations.turn_off_api_led_off_post.Input) async throws -> Operations.turn_off_api_led_off_post.Output
    /// Set Color
    ///
    /// - Remark: HTTP `POST /api/led/color`.
    /// - Remark: Generated from `#/paths//api/led/color/post(set_color_api_led_color_post)`.
    func set_color_api_led_color_post(_ input: Operations.set_color_api_led_color_post.Input) async throws -> Operations.set_color_api_led_color_post.Output
    /// Pulse
    ///
    /// - Remark: HTTP `POST /api/led/pulse`.
    /// - Remark: Generated from `#/paths//api/led/pulse/post(pulse_api_led_pulse_post)`.
    func pulse_api_led_pulse_post(_ input: Operations.pulse_api_led_pulse_post.Input) async throws -> Operations.pulse_api_led_pulse_post.Output
    /// Rainbow
    ///
    /// - Remark: HTTP `POST /api/led/rainbow`.
    /// - Remark: Generated from `#/paths//api/led/rainbow/post(rainbow_api_led_rainbow_post)`.
    func rainbow_api_led_rainbow_post(_ input: Operations.rainbow_api_led_rainbow_post.Input) async throws -> Operations.rainbow_api_led_rainbow_post.Output
    /// Get Scenes
    ///
    /// - Remark: HTTP `GET /api/scenes`.
    /// - Remark: Generated from `#/paths//api/scenes/get(get_scenes_api_scenes_get)`.
    func get_scenes_api_scenes_get(_ input: Operations.get_scenes_api_scenes_get.Input) async throws -> Operations.get_scenes_api_scenes_get.Output
    /// Play Scene
    ///
    /// - Remark: HTTP `POST /api/scenes/{scene_name}/play`.
    /// - Remark: Generated from `#/paths//api/scenes/{scene_name}/play/post(play_scene_api_scenes__scene_name__play_post)`.
    func play_scene_api_scenes__scene_name__play_post(_ input: Operations.play_scene_api_scenes__scene_name__play_post.Input) async throws -> Operations.play_scene_api_scenes__scene_name__play_post.Output
    /// Get Sounds
    ///
    /// - Remark: HTTP `GET /api/available-sounds`.
    /// - Remark: Generated from `#/paths//api/available-sounds/get(get_sounds_api_available_sounds_get)`.
    func get_sounds_api_available_sounds_get(_ input: Operations.get_sounds_api_available_sounds_get.Input) async throws -> Operations.get_sounds_api_available_sounds_get.Output
    /// Play Sound
    ///
    /// - Remark: HTTP `POST /api/play-sound/{file_name}`.
    /// - Remark: Generated from `#/paths//api/play-sound/{file_name}/post(play_sound_api_play_sound__file_name__post)`.
    func play_sound_api_play_sound__file_name__post(_ input: Operations.play_sound_api_play_sound__file_name__post.Input) async throws -> Operations.play_sound_api_play_sound__file_name__post.Output
    /// Stop Sound
    ///
    /// - Remark: HTTP `POST /api/stop-sound`.
    /// - Remark: Generated from `#/paths//api/stop-sound/post(stop_sound_api_stop_sound_post)`.
    func stop_sound_api_stop_sound_post(_ input: Operations.stop_sound_api_stop_sound_post.Input) async throws -> Operations.stop_sound_api_stop_sound_post.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Read Root
    ///
    /// - Remark: HTTP `GET /`.
    /// - Remark: Generated from `#/paths///get(read_root__get)`.
    public func read_root__get(headers: Operations.read_root__get.Input.Headers = .init()) async throws -> Operations.read_root__get.Output {
        try await read_root__get(Operations.read_root__get.Input(headers: headers))
    }
    /// Get Led Sections
    ///
    /// - Remark: HTTP `GET /api/led/sections`.
    /// - Remark: Generated from `#/paths//api/led/sections/get(get_led_sections_api_led_sections_get)`.
    public func get_led_sections_api_led_sections_get(headers: Operations.get_led_sections_api_led_sections_get.Input.Headers = .init()) async throws -> Operations.get_led_sections_api_led_sections_get.Output {
        try await get_led_sections_api_led_sections_get(Operations.get_led_sections_api_led_sections_get.Input(headers: headers))
    }
    /// Turn On
    ///
    /// - Remark: HTTP `POST /api/led/on`.
    /// - Remark: Generated from `#/paths//api/led/on/post(turn_on_api_led_on_post)`.
    public func turn_on_api_led_on_post(headers: Operations.turn_on_api_led_on_post.Input.Headers = .init()) async throws -> Operations.turn_on_api_led_on_post.Output {
        try await turn_on_api_led_on_post(Operations.turn_on_api_led_on_post.Input(headers: headers))
    }
    /// Turn Off
    ///
    /// - Remark: HTTP `POST /api/led/off`.
    /// - Remark: Generated from `#/paths//api/led/off/post(turn_off_api_led_off_post)`.
    public func turn_off_api_led_off_post(headers: Operations.turn_off_api_led_off_post.Input.Headers = .init()) async throws -> Operations.turn_off_api_led_off_post.Output {
        try await turn_off_api_led_off_post(Operations.turn_off_api_led_off_post.Input(headers: headers))
    }
    /// Set Color
    ///
    /// - Remark: HTTP `POST /api/led/color`.
    /// - Remark: Generated from `#/paths//api/led/color/post(set_color_api_led_color_post)`.
    public func set_color_api_led_color_post(
        headers: Operations.set_color_api_led_color_post.Input.Headers = .init(),
        body: Operations.set_color_api_led_color_post.Input.Body
    ) async throws -> Operations.set_color_api_led_color_post.Output {
        try await set_color_api_led_color_post(Operations.set_color_api_led_color_post.Input(
            headers: headers,
            body: body
        ))
    }
    /// Pulse
    ///
    /// - Remark: HTTP `POST /api/led/pulse`.
    /// - Remark: Generated from `#/paths//api/led/pulse/post(pulse_api_led_pulse_post)`.
    public func pulse_api_led_pulse_post(
        query: Operations.pulse_api_led_pulse_post.Input.Query = .init(),
        headers: Operations.pulse_api_led_pulse_post.Input.Headers = .init()
    ) async throws -> Operations.pulse_api_led_pulse_post.Output {
        try await pulse_api_led_pulse_post(Operations.pulse_api_led_pulse_post.Input(
            query: query,
            headers: headers
        ))
    }
    /// Rainbow
    ///
    /// - Remark: HTTP `POST /api/led/rainbow`.
    /// - Remark: Generated from `#/paths//api/led/rainbow/post(rainbow_api_led_rainbow_post)`.
    public func rainbow_api_led_rainbow_post(
        query: Operations.rainbow_api_led_rainbow_post.Input.Query = .init(),
        headers: Operations.rainbow_api_led_rainbow_post.Input.Headers = .init()
    ) async throws -> Operations.rainbow_api_led_rainbow_post.Output {
        try await rainbow_api_led_rainbow_post(Operations.rainbow_api_led_rainbow_post.Input(
            query: query,
            headers: headers
        ))
    }
    /// Get Scenes
    ///
    /// - Remark: HTTP `GET /api/scenes`.
    /// - Remark: Generated from `#/paths//api/scenes/get(get_scenes_api_scenes_get)`.
    public func get_scenes_api_scenes_get(headers: Operations.get_scenes_api_scenes_get.Input.Headers = .init()) async throws -> Operations.get_scenes_api_scenes_get.Output {
        try await get_scenes_api_scenes_get(Operations.get_scenes_api_scenes_get.Input(headers: headers))
    }
    /// Play Scene
    ///
    /// - Remark: HTTP `POST /api/scenes/{scene_name}/play`.
    /// - Remark: Generated from `#/paths//api/scenes/{scene_name}/play/post(play_scene_api_scenes__scene_name__play_post)`.
    public func play_scene_api_scenes__scene_name__play_post(
        path: Operations.play_scene_api_scenes__scene_name__play_post.Input.Path,
        headers: Operations.play_scene_api_scenes__scene_name__play_post.Input.Headers = .init()
    ) async throws -> Operations.play_scene_api_scenes__scene_name__play_post.Output {
        try await play_scene_api_scenes__scene_name__play_post(Operations.play_scene_api_scenes__scene_name__play_post.Input(
            path: path,
            headers: headers
        ))
    }
    /// Get Sounds
    ///
    /// - Remark: HTTP `GET /api/available-sounds`.
    /// - Remark: Generated from `#/paths//api/available-sounds/get(get_sounds_api_available_sounds_get)`.
    public func get_sounds_api_available_sounds_get(headers: Operations.get_sounds_api_available_sounds_get.Input.Headers = .init()) async throws -> Operations.get_sounds_api_available_sounds_get.Output {
        try await get_sounds_api_available_sounds_get(Operations.get_sounds_api_available_sounds_get.Input(headers: headers))
    }
    /// Play Sound
    ///
    /// - Remark: HTTP `POST /api/play-sound/{file_name}`.
    /// - Remark: Generated from `#/paths//api/play-sound/{file_name}/post(play_sound_api_play_sound__file_name__post)`.
    public func play_sound_api_play_sound__file_name__post(
        path: Operations.play_sound_api_play_sound__file_name__post.Input.Path,
        headers: Operations.play_sound_api_play_sound__file_name__post.Input.Headers = .init()
    ) async throws -> Operations.play_sound_api_play_sound__file_name__post.Output {
        try await play_sound_api_play_sound__file_name__post(Operations.play_sound_api_play_sound__file_name__post.Input(
            path: path,
            headers: headers
        ))
    }
    /// Stop Sound
    ///
    /// - Remark: HTTP `POST /api/stop-sound`.
    /// - Remark: Generated from `#/paths//api/stop-sound/post(stop_sound_api_stop_sound_post)`.
    public func stop_sound_api_stop_sound_post(headers: Operations.stop_sound_api_stop_sound_post.Input.Headers = .init()) async throws -> Operations.stop_sound_api_stop_sound_post.Output {
        try await stop_sound_api_stop_sound_post(Operations.stop_sound_api_stop_sound_post.Input(headers: headers))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/Color`.
        public struct Color: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Color/r`.
            public var r: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Color/g`.
            public var g: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Color/b`.
            public var b: Swift.Int
            /// Creates a new `Color`.
            ///
            /// - Parameters:
            ///   - r:
            ///   - g:
            ///   - b:
            public init(
                r: Swift.Int,
                g: Swift.Int,
                b: Swift.Int
            ) {
                self.r = r
                self.g = g
                self.b = b
            }
            public enum CodingKeys: String, CodingKey {
                case r
                case g
                case b
            }
        }
        /// - Remark: Generated from `#/components/schemas/HTTPValidationError`.
        public struct HTTPValidationError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/HTTPValidationError/detail`.
            public var detail: [Components.Schemas.ValidationError]?
            /// Creates a new `HTTPValidationError`.
            ///
            /// - Parameters:
            ///   - detail:
            public init(detail: [Components.Schemas.ValidationError]? = nil) {
                self.detail = detail
            }
            public enum CodingKeys: String, CodingKey {
                case detail
            }
        }
        /// - Remark: Generated from `#/components/schemas/LEDSection`.
        public struct LEDSection: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/LEDSection/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/LEDSection/count`.
            public var count: Swift.Int
            /// Creates a new `LEDSection`.
            ///
            /// - Parameters:
            ///   - name:
            ///   - count:
            public init(
                name: Swift.String,
                count: Swift.Int
            ) {
                self.name = name
                self.count = count
            }
            public enum CodingKeys: String, CodingKey {
                case name
                case count
            }
        }
        /// - Remark: Generated from `#/components/schemas/Sound`.
        public struct Sound: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Sound/fileName`.
            public var fileName: Swift.String
            /// - Remark: Generated from `#/components/schemas/Sound/friendlyName`.
            public var friendlyName: Swift.String
            /// Creates a new `Sound`.
            ///
            /// - Parameters:
            ///   - fileName:
            ///   - friendlyName:
            public init(
                fileName: Swift.String,
                friendlyName: Swift.String
            ) {
                self.fileName = fileName
                self.friendlyName = friendlyName
            }
            public enum CodingKeys: String, CodingKey {
                case fileName
                case friendlyName
            }
        }
        /// - Remark: Generated from `#/components/schemas/ValidationError`.
        public struct ValidationError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ValidationError/locPayload`.
            public struct locPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/ValidationError/locPayload/value1`.
                public var value1: Swift.String?
                /// - Remark: Generated from `#/components/schemas/ValidationError/locPayload/value2`.
                public var value2: Swift.Int?
                /// Creates a new `locPayloadPayload`.
                ///
                /// - Parameters:
                ///   - value1:
                ///   - value2:
                public init(
                    value1: Swift.String? = nil,
                    value2: Swift.Int? = nil
                ) {
                    self.value1 = value1
                    self.value2 = value2
                }
                public init(from decoder: any Decoder) throws {
                    var errors: [any Error] = []
                    do {
                        self.value1 = try decoder.decodeFromSingleValueContainer()
                    } catch {
                        errors.append(error)
                    }
                    do {
                        self.value2 = try decoder.decodeFromSingleValueContainer()
                    } catch {
                        errors.append(error)
                    }
                    try Swift.DecodingError.verifyAtLeastOneSchemaIsNotNil(
                        [
                            self.value1,
                            self.value2
                        ],
                        type: Self.self,
                        codingPath: decoder.codingPath,
                        errors: errors
                    )
                }
                public func encode(to encoder: any Encoder) throws {
                    try encoder.encodeFirstNonNilValueToSingleValueContainer([
                        self.value1,
                        self.value2
                    ])
                }
            }
            /// - Remark: Generated from `#/components/schemas/ValidationError/loc`.
            public typealias locPayload = [Components.Schemas.ValidationError.locPayloadPayload]
            /// - Remark: Generated from `#/components/schemas/ValidationError/loc`.
            public var loc: Components.Schemas.ValidationError.locPayload
            /// - Remark: Generated from `#/components/schemas/ValidationError/msg`.
            public var msg: Swift.String
            /// - Remark: Generated from `#/components/schemas/ValidationError/type`.
            public var _type: Swift.String
            /// Creates a new `ValidationError`.
            ///
            /// - Parameters:
            ///   - loc:
            ///   - msg:
            ///   - _type:
            public init(
                loc: Components.Schemas.ValidationError.locPayload,
                msg: Swift.String,
                _type: Swift.String
            ) {
                self.loc = loc
                self.msg = msg
                self._type = _type
            }
            public enum CodingKeys: String, CodingKey {
                case loc
                case msg
                case _type = "type"
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// Read Root
    ///
    /// - Remark: HTTP `GET /`.
    /// - Remark: Generated from `#/paths///get(read_root__get)`.
    public enum read_root__get {
        public static let id: Swift.String = "read_root__get"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.read_root__get.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.read_root__get.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.read_root__get.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.read_root__get.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/GET/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.read_root__get.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.read_root__get.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths///get(read_root__get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.read_root__get.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.read_root__get.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Get Led Sections
    ///
    /// - Remark: HTTP `GET /api/led/sections`.
    /// - Remark: Generated from `#/paths//api/led/sections/get(get_led_sections_api_led_sections_get)`.
    public enum get_led_sections_api_led_sections_get {
        public static let id: Swift.String = "get_led_sections_api_led_sections_get"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/led/sections/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.get_led_sections_api_led_sections_get.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.get_led_sections_api_led_sections_get.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.get_led_sections_api_led_sections_get.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.get_led_sections_api_led_sections_get.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/sections/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/sections/GET/responses/200/content/application\/json`.
                    case json([Components.Schemas.LEDSection])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: [Components.Schemas.LEDSection] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.get_led_sections_api_led_sections_get.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.get_led_sections_api_led_sections_get.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/led/sections/get(get_led_sections_api_led_sections_get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.get_led_sections_api_led_sections_get.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.get_led_sections_api_led_sections_get.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Turn On
    ///
    /// - Remark: HTTP `POST /api/led/on`.
    /// - Remark: Generated from `#/paths//api/led/on/post(turn_on_api_led_on_post)`.
    public enum turn_on_api_led_on_post {
        public static let id: Swift.String = "turn_on_api_led_on_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/led/on/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.turn_on_api_led_on_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.turn_on_api_led_on_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.turn_on_api_led_on_post.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.turn_on_api_led_on_post.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/on/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/on/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.turn_on_api_led_on_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.turn_on_api_led_on_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/led/on/post(turn_on_api_led_on_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.turn_on_api_led_on_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.turn_on_api_led_on_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/on/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/on/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.turn_on_api_led_on_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.turn_on_api_led_on_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//api/led/on/post(turn_on_api_led_on_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.turn_on_api_led_on_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.turn_on_api_led_on_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Turn Off
    ///
    /// - Remark: HTTP `POST /api/led/off`.
    /// - Remark: Generated from `#/paths//api/led/off/post(turn_off_api_led_off_post)`.
    public enum turn_off_api_led_off_post {
        public static let id: Swift.String = "turn_off_api_led_off_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/led/off/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.turn_off_api_led_off_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.turn_off_api_led_off_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.turn_off_api_led_off_post.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.turn_off_api_led_off_post.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/off/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/off/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.turn_off_api_led_off_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.turn_off_api_led_off_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/led/off/post(turn_off_api_led_off_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.turn_off_api_led_off_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.turn_off_api_led_off_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/off/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/off/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.turn_off_api_led_off_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.turn_off_api_led_off_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//api/led/off/post(turn_off_api_led_off_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.turn_off_api_led_off_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.turn_off_api_led_off_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Set Color
    ///
    /// - Remark: HTTP `POST /api/led/color`.
    /// - Remark: Generated from `#/paths//api/led/color/post(set_color_api_led_color_post)`.
    public enum set_color_api_led_color_post {
        public static let id: Swift.String = "set_color_api_led_color_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/led/color/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.set_color_api_led_color_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.set_color_api_led_color_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.set_color_api_led_color_post.Input.Headers
            /// - Remark: Generated from `#/paths/api/led/color/POST/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/color/POST/requestBody/content/application\/json`.
                case json(Components.Schemas.Color)
            }
            public var body: Operations.set_color_api_led_color_post.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.set_color_api_led_color_post.Input.Headers = .init(),
                body: Operations.set_color_api_led_color_post.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/color/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/color/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.set_color_api_led_color_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.set_color_api_led_color_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/led/color/post(set_color_api_led_color_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.set_color_api_led_color_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.set_color_api_led_color_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/color/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/color/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.set_color_api_led_color_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.set_color_api_led_color_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//api/led/color/post(set_color_api_led_color_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.set_color_api_led_color_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.set_color_api_led_color_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Pulse
    ///
    /// - Remark: HTTP `POST /api/led/pulse`.
    /// - Remark: Generated from `#/paths//api/led/pulse/post(pulse_api_led_pulse_post)`.
    public enum pulse_api_led_pulse_post {
        public static let id: Swift.String = "pulse_api_led_pulse_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/led/pulse/POST/query`.
            public struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/pulse/POST/query/duration`.
                public var duration: Swift.Double?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - duration:
                public init(duration: Swift.Double? = nil) {
                    self.duration = duration
                }
            }
            public var query: Operations.pulse_api_led_pulse_post.Input.Query
            /// - Remark: Generated from `#/paths/api/led/pulse/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.pulse_api_led_pulse_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.pulse_api_led_pulse_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.pulse_api_led_pulse_post.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            public init(
                query: Operations.pulse_api_led_pulse_post.Input.Query = .init(),
                headers: Operations.pulse_api_led_pulse_post.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/pulse/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/pulse/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.pulse_api_led_pulse_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.pulse_api_led_pulse_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/led/pulse/post(pulse_api_led_pulse_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.pulse_api_led_pulse_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.pulse_api_led_pulse_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/pulse/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/pulse/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.pulse_api_led_pulse_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.pulse_api_led_pulse_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//api/led/pulse/post(pulse_api_led_pulse_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.pulse_api_led_pulse_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.pulse_api_led_pulse_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Rainbow
    ///
    /// - Remark: HTTP `POST /api/led/rainbow`.
    /// - Remark: Generated from `#/paths//api/led/rainbow/post(rainbow_api_led_rainbow_post)`.
    public enum rainbow_api_led_rainbow_post {
        public static let id: Swift.String = "rainbow_api_led_rainbow_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/led/rainbow/POST/query`.
            public struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/rainbow/POST/query/duration`.
                public var duration: Swift.Double?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - duration:
                public init(duration: Swift.Double? = nil) {
                    self.duration = duration
                }
            }
            public var query: Operations.rainbow_api_led_rainbow_post.Input.Query
            /// - Remark: Generated from `#/paths/api/led/rainbow/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.rainbow_api_led_rainbow_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.rainbow_api_led_rainbow_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.rainbow_api_led_rainbow_post.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            public init(
                query: Operations.rainbow_api_led_rainbow_post.Input.Query = .init(),
                headers: Operations.rainbow_api_led_rainbow_post.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/rainbow/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/rainbow/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.rainbow_api_led_rainbow_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.rainbow_api_led_rainbow_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/led/rainbow/post(rainbow_api_led_rainbow_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.rainbow_api_led_rainbow_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.rainbow_api_led_rainbow_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/led/rainbow/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/led/rainbow/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.rainbow_api_led_rainbow_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.rainbow_api_led_rainbow_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//api/led/rainbow/post(rainbow_api_led_rainbow_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.rainbow_api_led_rainbow_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.rainbow_api_led_rainbow_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Get Scenes
    ///
    /// - Remark: HTTP `GET /api/scenes`.
    /// - Remark: Generated from `#/paths//api/scenes/get(get_scenes_api_scenes_get)`.
    public enum get_scenes_api_scenes_get {
        public static let id: Swift.String = "get_scenes_api_scenes_get"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/scenes/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.get_scenes_api_scenes_get.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.get_scenes_api_scenes_get.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.get_scenes_api_scenes_get.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.get_scenes_api_scenes_get.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/scenes/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/scenes/GET/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.get_scenes_api_scenes_get.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.get_scenes_api_scenes_get.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/scenes/get(get_scenes_api_scenes_get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.get_scenes_api_scenes_get.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.get_scenes_api_scenes_get.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Play Scene
    ///
    /// - Remark: HTTP `POST /api/scenes/{scene_name}/play`.
    /// - Remark: Generated from `#/paths//api/scenes/{scene_name}/play/post(play_scene_api_scenes__scene_name__play_post)`.
    public enum play_scene_api_scenes__scene_name__play_post {
        public static let id: Swift.String = "play_scene_api_scenes__scene_name__play_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/scenes/{scene_name}/play/POST/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/scenes/{scene_name}/play/POST/path/scene_name`.
                public var scene_name: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - scene_name:
                public init(scene_name: Swift.String) {
                    self.scene_name = scene_name
                }
            }
            public var path: Operations.play_scene_api_scenes__scene_name__play_post.Input.Path
            /// - Remark: Generated from `#/paths/api/scenes/{scene_name}/play/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.play_scene_api_scenes__scene_name__play_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.play_scene_api_scenes__scene_name__play_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.play_scene_api_scenes__scene_name__play_post.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.play_scene_api_scenes__scene_name__play_post.Input.Path,
                headers: Operations.play_scene_api_scenes__scene_name__play_post.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/scenes/{scene_name}/play/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/scenes/{scene_name}/play/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.play_scene_api_scenes__scene_name__play_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.play_scene_api_scenes__scene_name__play_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/scenes/{scene_name}/play/post(play_scene_api_scenes__scene_name__play_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.play_scene_api_scenes__scene_name__play_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.play_scene_api_scenes__scene_name__play_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/scenes/{scene_name}/play/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/scenes/{scene_name}/play/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.play_scene_api_scenes__scene_name__play_post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.play_scene_api_scenes__scene_name__play_post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//api/scenes/{scene_name}/play/post(play_scene_api_scenes__scene_name__play_post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.play_scene_api_scenes__scene_name__play_post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.play_scene_api_scenes__scene_name__play_post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Get Sounds
    ///
    /// - Remark: HTTP `GET /api/available-sounds`.
    /// - Remark: Generated from `#/paths//api/available-sounds/get(get_sounds_api_available_sounds_get)`.
    public enum get_sounds_api_available_sounds_get {
        public static let id: Swift.String = "get_sounds_api_available_sounds_get"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/available-sounds/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.get_sounds_api_available_sounds_get.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.get_sounds_api_available_sounds_get.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.get_sounds_api_available_sounds_get.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.get_sounds_api_available_sounds_get.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/available-sounds/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/available-sounds/GET/responses/200/content/application\/json`.
                    case json([Components.Schemas.Sound])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: [Components.Schemas.Sound] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.get_sounds_api_available_sounds_get.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.get_sounds_api_available_sounds_get.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/available-sounds/get(get_sounds_api_available_sounds_get)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.get_sounds_api_available_sounds_get.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.get_sounds_api_available_sounds_get.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Play Sound
    ///
    /// - Remark: HTTP `POST /api/play-sound/{file_name}`.
    /// - Remark: Generated from `#/paths//api/play-sound/{file_name}/post(play_sound_api_play_sound__file_name__post)`.
    public enum play_sound_api_play_sound__file_name__post {
        public static let id: Swift.String = "play_sound_api_play_sound__file_name__post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/play-sound/{file_name}/POST/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/play-sound/{file_name}/POST/path/file_name`.
                public var file_name: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - file_name:
                public init(file_name: Swift.String) {
                    self.file_name = file_name
                }
            }
            public var path: Operations.play_sound_api_play_sound__file_name__post.Input.Path
            /// - Remark: Generated from `#/paths/api/play-sound/{file_name}/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.play_sound_api_play_sound__file_name__post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.play_sound_api_play_sound__file_name__post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.play_sound_api_play_sound__file_name__post.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.play_sound_api_play_sound__file_name__post.Input.Path,
                headers: Operations.play_sound_api_play_sound__file_name__post.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/play-sound/{file_name}/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/play-sound/{file_name}/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.play_sound_api_play_sound__file_name__post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.play_sound_api_play_sound__file_name__post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/play-sound/{file_name}/post(play_sound_api_play_sound__file_name__post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.play_sound_api_play_sound__file_name__post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.play_sound_api_play_sound__file_name__post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct UnprocessableContent: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/play-sound/{file_name}/POST/responses/422/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/play-sound/{file_name}/POST/responses/422/content/application\/json`.
                    case json(Components.Schemas.HTTPValidationError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.HTTPValidationError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.play_sound_api_play_sound__file_name__post.Output.UnprocessableContent.Body
                /// Creates a new `UnprocessableContent`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.play_sound_api_play_sound__file_name__post.Output.UnprocessableContent.Body) {
                    self.body = body
                }
            }
            /// Validation Error
            ///
            /// - Remark: Generated from `#/paths//api/play-sound/{file_name}/post(play_sound_api_play_sound__file_name__post)/responses/422`.
            ///
            /// HTTP response code: `422 unprocessableContent`.
            case unprocessableContent(Operations.play_sound_api_play_sound__file_name__post.Output.UnprocessableContent)
            /// The associated value of the enum case if `self` is `.unprocessableContent`.
            ///
            /// - Throws: An error if `self` is not `.unprocessableContent`.
            /// - SeeAlso: `.unprocessableContent`.
            public var unprocessableContent: Operations.play_sound_api_play_sound__file_name__post.Output.UnprocessableContent {
                get throws {
                    switch self {
                    case let .unprocessableContent(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unprocessableContent",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Stop Sound
    ///
    /// - Remark: HTTP `POST /api/stop-sound`.
    /// - Remark: Generated from `#/paths//api/stop-sound/post(stop_sound_api_stop_sound_post)`.
    public enum stop_sound_api_stop_sound_post {
        public static let id: Swift.String = "stop_sound_api_stop_sound_post"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/stop-sound/POST/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.stop_sound_api_stop_sound_post.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.stop_sound_api_stop_sound_post.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.stop_sound_api_stop_sound_post.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            public init(headers: Operations.stop_sound_api_stop_sound_post.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/api/stop-sound/POST/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/api/stop-sound/POST/responses/200/content/application\/json`.
                    case json(OpenAPIRuntime.OpenAPIValueContainer)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: OpenAPIRuntime.OpenAPIValueContainer {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.stop_sound_api_stop_sound_post.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.stop_sound_api_stop_sound_post.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successful Response
            ///
            /// - Remark: Generated from `#/paths//api/stop-sound/post(stop_sound_api_stop_sound_post)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.stop_sound_api_stop_sound_post.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.stop_sound_api_stop_sound_post.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
